#DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: green-deployment
  template:
    metadata:
      labels: 
        name: green-deployment
    spec:
      containers:
        - name: green-container
          image: devopswithcloudhub/nginx:green
          ports:
            - containerPort: 80
---
#SERVICE
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  selector:
    name: green-deployment
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
---
#INGRESS-CONTROLLER
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: green-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: green-service
            port:
              number: 80