#creating a clusterrole for giving access to user for cluster scopelevel access(in this we don't need namespace)
#clusterrole for cluster level access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-cluster-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get","watch","list"]
---
#ClusterRolebinding (giving permissions to person to above role for cluster level)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-role-binding
subjects:
- kind: User
  name: sai
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pvc-cluster-role
  apiGroup: rbac.authorization.k8s.io
