apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ingress-orange
spec:
  replicas: 1
  selector:
     matchLabels:
       app: orange-app
  template:
    metadata:
      labels:
        app: orange-app
    spec:
      containers:
        - name: orange-app
          image: devopswithcloudhub/nginx:orange #blue-app
          ports:
            - containerPort: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: deploy-ingress-orange
spec:
  selector:
     app: orange-app
  type: ClusterIP
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP