apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: nagasaivardhan/java-gradle:v1
          ports:
            - containerPort: 8080