apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-app
  template:
    metadata:
      labels:
        app: new-app
    spec:
     volumes:
       - name: my-volume
         persistentVolumeClaim:
           claimName: pvc-claim-default
     containers:
       - name: nginx-webserver
         image: nginx
         ports:
          - containerPort: 80
         volumeMounts:
          - name: my-volume
            mountPath: "/vardhan"