#in dynamic provisioning you don't need to create pv when you create pvc it automatically creates pv(disk in GCP)in GKE
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: faster #it should match storageclass in our cluster