apiVersion: v1
kind: Pod
metadata:
  name: quareented
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "125m"
          memory: "250Mi"
        limits:
          cpu: "125m"
          memory: "250Mi"