apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vardhan
  name: pod-reader
rules:
- apiGroups: ["","apps"]
  resources: ["pods","deployment"]
  verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: vardhan
subjects:
- kind: User
  name: sai
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
