apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-deploy-configmap
spec:
  replicas: 2
  selector:
    matchLabels:
       app: env-deploy-configmap
  template:
    metadata:
      labels:
        app: env-deploy-configmap
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ['sh','-c','while true; do echo i rolled to $MYAPPSTAGE and My password is $MYPASSWORD; sleep 10; done']
          env:
           - name: MYAPPSTAGE
             valueFrom:
               configMapKeyRef:
                 name: app-configmap  #name of configmap which created before
                 key: APP_STAGE  # key from configmap which created before
           - name: MYPASSWORD 
             valueFrom:
               secretKeyRef: 
                 name: secret  #name of secret which created before
                 key:  DB_PASS  # key from secret which created beforar
                 